const AIRTABLE_API_KEY = process.env.AIRTABLE_API_KEY;
const AIRTABLE_BASE = process.env.AIRTABLE_BASE;
const BREAKPOINTS = {
  SMALL_DEVICES: "576px",
  MEDIUM_DEVICES: "768px",
  LARGE_DEVICES: "992px",
  EXTRA_LARGE_DEVICES: "1200px",
};
const GA_TRACKING_ID = "UA-173170780-1";

export default { AIRTABLE_API_KEY, AIRTABLE_BASE, BREAKPOINTS, GA_TRACKING_ID };
